### ISSUE TITLE
The public_orderbook function does not appear to be passing the level to the CBP API

### ISSUE THREAD

**Issue by jeremiahsb** [DheerajAgarwal/rgdax#15]
In version 1.1.0, using the public_orderbook for BTC-USD and level = 1, yields a tibble with 1 row, 7 columns. This is to be expected. Using level 2 yields the same output. I believe the issue is in the parse_response function. It doesn't seem to be passing the query parameter to the API. manually running httr::GET("https://api.pro.coinbase.com/products/BTC-USD/book?level=2") then passing the response into content() yields the expected 50 row by 7 columns.

**Comment by DheerajAgarwal** [comment]
Hi. This is now fixed and I am testing the code for CRAN push. The issue was that the query parameter was getting set as NULL. I have pushed teh changes to dev, so should be good to go for meanwhile.
