### ISSUE TITLE
STOP Orders

### ISSUE THREAD

**Issue by beavertrapper07** [DheerajAgarwal/rgdax#2]
Great work with this package. When do you think you'll code in the ability to enter STOP orders? That would be awesome!

Thanks again

**Comment by DheerajAgarwal** [comment]
A stop market order can be placed today(which is technically a limit order), however a stop limit order cannot be added. Based on the feedback so far, it looks like using `httr` based auth might be more flexible than the `RCurl` to be able to pass additional params. Will try and figure this out but no ETA.

**Comment by beavertrapper07** [comment]
Awesome!

**Comment by DheerajAgarwal** [comment]
@beavertrapper07 Stop orders have been added and the new package version is now available on CRAN. I have tested it in my capacity and it seems to be working fine, however it can always use additional eyes, so keep that in mind while working with it.
