### ISSUE TITLE
parse_response query argument

### ISSUE THREAD

**Issue by southernt** [DheerajAgarwal/rgdax#21]
getting error when running `public_info()`:

Error in build_url(utils::modifyList(old, new)) : is.character(query) is not TRUE

This error goes away and the `public_info()` starts working appropriately for me when I set `query = NA_character` instead of NA inside of the `parse_response()` function.

Using R 4.1.0 & rgdax 1.2.1 on Mac

**Comment by DheerajAgarwal** [comment]
Agreed. There has been some changes with `NA` which has caused a lot of functions to misbehave. I have changed the `query = NULL` for consistency with changes else where. Testing it locally works. I have pushed the code changes to `dev branch`
