### ISSUE TITLE
error with some public_ functions

### ISSUE THREAD

**Issue by chrisjw18** [DheerajAgarwal/rgdax#22]
Hi,

Working with rgdax_1.2.1 on Rstudio with the below config:
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

The majority of the rgdax functions work fine, but the following are creating an error (shown below):
public_daystats()
public_tickers()

Example call and the error given:
> public_ticker(product_id = "BTC-USD")
Error in build_url(utils::modifyList(old, new)) : 
  is.character(query) is not TRUE

The same error is shown for both of these functions no matter the coin pair input..

Many thanks with any help on this.

Chris.

**Comment by DheerajAgarwal** [comment]
@chrisjw18 I have tried this on the latest and unable to reproduce the issue. When I ran `public_ticker` and `public_daystats` after unloading `rgdax` and re-installing the latest from CRAN, it ran without any issues. Could you try unistalling the module then reinstalling it before trying again and let me know if this still throws up the error.

**Comment by DheerajAgarwal** [comment]
@chrisjw18 . I was able to reproduce it with some hit and trial. If you install the code from `dev` branch hopefully the issues should be resolved. 

```
library(devtools)
install_github("DheerajAgarwal/rgdax", ref="dev")
```


I will keep it in `dev` for some time before pushing it to CRAN.

**Comment by chrisjw18** [comment]
Sorry for my slow reply and many thanks - it now works a treat. Great library - thanks for all your work.

Chris.
