### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by Guceri** [DheerajAgarwal/rgdax#7]
Hi,
I am running a simple shiny app and I periodically get a timeout error every once in a while (average 1 per day).  I make about 3-10 api calls every 5 seconds, so it clearly isn't often, but it only needs to happen once to kill the app from running.  Is there a timeout value that can be increases on any one of the api requests (or maybe a trycatch could work some how)?  I noticed that the httr package has an option to create the timeout value, but I am not too sure if you are using that for this package or not.  Eitherway, let me know!

**Comment by DheerajAgarwal** [comment]
@Guceri Do you know specifically which functions may be causing the issue? Reading the httr documentation, I can't see the default time out setting so I will set it to 5 seconds as a starting point and let you know once ready. You may have to install the package from github to test it out. Coinbase pro also [throttles the request](https://docs.pro.coinbase.com/#rate-limits) but given your frequency I do not suspect it to be an issue.

**Comment by Guceri** [comment]
I am not hitting any api rate limits that I am aware off. The message in
the console is (for what its worth):

Warning: Error in : Gateway Time-out
  54: <Anonymous>

The possible functions given the crash point would include:

   - accounts() - pulled every 5 seconds
   - open_orders()
      - potentially called twice with a 1 sec Sys.sleep() gap in between
      each request
   - public_orderbook()


I will try and debug to see which one is the potential trouble.  My first
thought was that since it is a warning, I could just wrap the functions in
a tryCatch and have it loop through again if a warning pops up, but I think
just increasing the timeout would be a more elegant solution to the issue.
Too many tryCatch's and the code starts to look messy.

"You may have to install the package from github to test it out."


Do you mean the modified rgdax package or are you referring to httr?  Let
me know when you have something and I can take a look.  I assume it just
requires adding a timeout variable to the GET ?

**Comment by Guceri** [comment]
The error seemed to be a little different last night:

Warning: Error in <Promise>: Operation timed out after 0 milliseconds with
0 out of 0 bytes received
  55: <Anonymous>

**Comment by DheerajAgarwal** [comment]
This issue was not reproducible. The package is undergoing major changes with respect to its endpoint connectivity. Please test this issue once the new stable version is released or on the current `dev` version.
